### ISSUE TITLE
Grid defaulting to font-size zero

### ISSUE THREAD

**Issue by ronnross** [suitcss/components-grid#33]
I'm attempting to use suitcss with react. I used npm to intstall 
```"suitcss-components": "^0.3.0",
    "suitcss-components-grid": "^2.0.2",```

I create a base.css that looks like 
```
@import '../../node_modules/suitcss-base';
@import '../../node_modules/suitcss-components-grid';

:root {
  --Grid-font-size: 1em;
  --base-font-size: 16px;
}
```
Even with the Grid-font-size the default font-size is 0. Therefore, when the grid renders it's not visible. Here is a sample of my react element

```
var React = require('react');
require('../suit/base.css');
var SuitCss = React.createClass({
  render: function() {
    return (
      <div>
        <div className="Grid [Grid--alignCenter|Grid--alignRight|Grid--alignMiddle|Grid--alignBottom]">
          <div className="Grid-cell u-size1of2 u-lg-size6of12">column 1</div>
          <div className="Grid-cell u-size1of2 u-lg-size4of12">column 2</div>
          <div className="Grid-cell u-size1of3 u-lg-size2of12">column 3</div>
          <div className="Grid-cell u-size1of3"></div>
        </div>
      </div>
    );
  }

});
```

Even when I change the font-size in dev tools the grid is still not working as I would expect. Is this a bug or something I don't understand about suit?

**Comment by magsout** [comment]
@ronnross You have to put `--Grid-font-size: 1em;` in rem and not em, because of : 

```
.Grid {
  font-size: 0; 
}
```

**Comment by ronnross** [comment]
Sorry, changed to 
`:root {
  --Grid-font-size: 1rem;
  --base-font-size: 16px;
}`

and still did not work . I'm no expert but why would the default font-size on a grid be 0?

**Comment by magsout** [comment]
Hum, to use `u-sizeXofY` don't forget to install https://github.com/suitcss/utils-size and https://github.com/suitcss/utils-offset

**Comment by magsout** [comment]
>and still did not work . I'm no expert but why would the default font-size on a grid be 0? 

To remove whitespace between Inline-Block `.Grid-cell`

**Comment by necolas** [comment]
Probably going to undo the `font-size:0` stuff soon. When you use a "good" templating system like the one in React or Closure's Soy templates, then it collapses whitespace by default and that's much more effective than the font-size (which is not perfect on Android). Plus, going to focus on flex-box grids going forward.
