### ISSUE TITLE
negative margin makes container larger than it should be

### ISSUE THREAD

**Issue by lifeiscontent** [suitcss/components-grid#36]
on the `.Grid--withGutter` class since there is a negative margin it actually draws the container to be larger than it would be without it. by doing this, each grid cell ends up rendering larger than they would without the negative margin.

anyway to fix this?

**Comment by mancinigianluca** [comment]
Use `overflow-x: hidden` or padding on the parent.

**Comment by simonsmith** [comment]
This is intentional behaviour often found in grid systems. The padding on each `Grid-cell` sets it back to the expected width.
