### ISSUE TITLE
Grid use of negative margins causes horizontal scrolling

### ISSUE THREAD

**Issue by jessetrippe** [suitcss/components-grid#41]
I've been working with SUIT for a while and have noticed that while using the old Grid (inline-block) and the new Grid (flexbox) with "Grid--withGutter" modifier a horizontal scroll appears due to the negative margin. I can set the body to overflow-x: hidden but that seems kind of hacky. Do you have any suggestions?

![screen shot 2016-03-30 at 12 59 54 pm](https://cloud.githubusercontent.com/assets/8770896/14155625/5aa1c296-f677-11e5-9097-01b9a6bb32a9.png)

**Comment by simonsmith** [comment]
Hey, thanks for the report. Is it possible to add this to an codepen or something so I can test it?

Could it be similar to this issue too? - https://github.com/suitcss/utils-size/issues/32

**Comment by jessetrippe** [comment]
Yes. It looks to be a duplicate issue. I have put together a demo on codepen. You can see that there is a slight horizontal scroll at the bottom.

http://codepen.io/anon/pen/jqLeOa

**Comment by simonsmith** [comment]
Thanks, I'll investigate this tomorrow.

**Comment by simonsmith** [comment]
After having a look at this I think it's the same issue as before, which is using `Grid--withGutter` on a container element. See my [comment](https://github.com/suitcss/utils-size/issues/32#issuecomment-164554541) in the other issue.

In your example the `withGutter` modifier on the containing `Grid` is unnecessary as there isn't two columns. The `header` element is the only one that makes use of `withGutter`.

This issue exists on any version of the Grid as `withGutter` applies a negative margin and shouldn't be used on a top level `Grid` component unless it has some form of `Container` component to manage the padding and or width. Example here - http://codepen.io/simonsmith/pen/VaMvPW

I don't think there is a bug here, but perhaps the documentation could make this clearer if people are getting tripped up by it.

**Comment by simonsmith** [comment]
@jessetrippe Any more comments? Will close otherwise :)
