### ISSUE TITLE
Fixed column width + fluid one

### ISSUE THREAD

**Issue by cmnstmntmn** [suitcss/components-grid#42]
what would be the correct aproach in order to get the following fluid markup, over the main layout ?

[ aside (containing ad) 300px ]  [ fluid (rest of the space) ]

![layout](https://cloud.githubusercontent.com/assets/2312755/14500016/08c31438-01a9-11e6-995a-06736663decb.png)

**Comment by simonsmith** [comment]
One route might be to implement your own fixed utilty:

``` css
.u-size3of12Fixed {
  width: 300px;
}
```

And then apply `sizeFill` on the content area:

``` html
<div class="Container">
  <div class="Grid Grid--withGutter">
    <div class="Grid-cell u-size3of12Fixed" style="background: red">fixed</div>
    <div class="Grid-cell u-sizeFill" style="background: green">Fluid</div>
  </div>
</div>
```

http://codepen.io/simonsmith/pen/zqWNxj

**Comment by cmnstmntmn** [comment]
great (;

-----Original Message-----
