### ISSUE TITLE
Grid / Grid-cel ignores u-sizeFull

### ISSUE THREAD

**Issue by cmnstmntmn** [suitcss/components-grid#45]
hei,

i'm having this markup

```html
<div class="Grid Grid--fit Grid--withGutter Grid--equalHeight">
	<div class="Grid-cell u-sizeFull">
		content
	</div>

	<div class="Grid-cell u-size1of2">
		content
	</div>

	<div class="Grid-cell u-size1of2">
		content		
	</div>
</div>	
```

this is what i get

![grid_not_ok](https://cloud.githubusercontent.com/assets/2312755/18585378/3c41d812-7c1f-11e6-948a-a62bf16e3de3.png)

this is the result expected

![grid](https://cloud.githubusercontent.com/assets/2312755/18585298/c6b4b7b8-7c1e-11e6-9288-a06f47892767.png)

**Comment by cmnstmntmn** [comment]
removing **.Grid--fit** solved the issue.

so this code, shows the expected result

```html
<div class="Grid Grid--withGutter Grid--equalHeight">
    <div class="Grid-cell u-sizeFull">
        content
    </div>

    <div class="Grid-cell u-size1of2">
        content
    </div>

    <div class="Grid-cell u-size1of2">
        content     
    </div>
</div> 
```

**Comment by simonsmith** [comment]
Cool, glad you solved it.

[utils-flex](https://github.com/suitcss/utils-flex) can also work with Grid if you need more granular flexbox control.

**Comment by cmnstmntmn** [comment]
i know, but i use it Grid because of it's **gutter** option
