### ISSUE TITLE
Layout broken using `Grid--withGutter`, in IE11

### ISSUE THREAD

**Issue by nadalsol** [suitcss/components-grid#49]
Hola,

First of all, this grid is very good, so thank you in advance for creating it :tophat:

Being said that, I recently discovered a bug using Internet Explorer 11 (Windows10), in conjunction with the `Grid--withGutter` modifier class. When using `<div class="Grid Grid--withGutter">` within an inner, the last column falls apart.

### The problem

Given this code...

#### HTML

```
<div class="Wrapper">
  <div class="u-inner">
    <div class="Grid Grid--withGutter">
      <div class="Grid-cell u-lg-size4of12">
        <p>Lorem</p>
      </div>
      <div class="Grid-cell u-lg-size4of12">
        <p>Ipsum</p>
      </div>
      <div class="Grid-cell u-lg-size4of12">
        <p>Dolor</p>
      </div>
    </div>
  </div>
</div>
```

#### CSS

```
* {
  box-sizing: border-box;
}

.Wrapper {
  max-width: 1200px;
  margin: 0 auto;
  background-color: white;
}

.u-inner {
  padding: 64px 16px;
}

p {
  background-color: gold;
}
```

This is what happens...

![grid-with-gutter-ie11-bug](https://user-images.githubusercontent.com/3439783/30174555-c45b0148-93fb-11e7-9cdf-63263450cc31.png)

### The cause

To be more specific, the problem seems to occur with the `width: calc(100% * 1 / 3) !important;` calculation (remember, IE11 only):

```
@media (min-width: 768px) {
  .u-lg-size1of3, .u-lg-size2of6, .u-lg-size4of12 {
    -ms-flex-preferred-size: auto !important;
    flex-basis: auto !important;
    width: calc(100% * 1 / 3) !important;
  }
}
```

If you take a look at the computed width in Chrome, it results in:

`width: 394.656px`

On the other hand, IE11 seems to compute this `calc` in a different way, so it results in:

`width: 378.67px;`

After some research, I realized IE have some troubles with sub-pixel rounding (just take a look at the "Known issues" tab in [Can I use](http://caniuse.com/#search=calc) site), so more than likely this could be the cause of the issue.

Have you thought in doing this calculation with a CSS pre-processor (Sass, PostCSS...), to return always the same pixel value?

Cheers

**Comment by simonsmith** [comment]
Hey @nadalsol,

Have you tried using [postcss-calc](https://github.com/postcss/postcss-calc) (used in the SUITCSS preprocessor) in your build step? This will precompute the values where possible and will likely fix this issue in IE11

Let me know

**Comment by nadalsol** [comment]
@simonsmith 

Godd point! I don't...

Let me try it, I will keep you posted.

**Comment by simonsmith** [comment]
Closing this out
