### ISSUE TITLE
Drop .Grid-cell

### ISSUE THREAD

**Issue by timkelty** [suitcss/components-grid#50]
I tend to think we should drop `.Grid-cell` and just use .Grid > *, since the nature of flexbox requires that it be a direct child.

`Grid-cell--center` could then also be dropped in favor of `u-flexExpand/u-flexExpandLeft/u-flexRight`, which gives you greater flexibility anyway.

Thoughts @simonsmith @giuseppeg?

**Comment by simonsmith** [comment]
@timkelty Sounds like a good idea to me. So you propose this pattern:

```html
<div class="Grid">
  <div class="u-size1of2">
    {{>partial}}
  </div>
</div>
```

**Comment by timkelty** [comment]
Yep!

Really all Grid is now is flexbox + gutters, with some helper modifiers, so I say lets take advantage of that and simplify.

I'll work on PR

**Comment by simonsmith** [comment]
Perfect. As long as we can replicate all the current functionality then it sounds good to me!

**Comment by giuseppeg** [comment]
Yup I like that!

**Comment by simonsmith** [comment]
I've got some time to work on this if you like @timkelty?

**Comment by timkelty** [comment]
@simonsmith sure!

Actually could prob use your help anyway: I looked into doing this super quickly, but realized the linter wouldn't allow `Component > *`, which I'm thinking it should, for instances like this.

**Comment by timkelty** [comment]
@simonsmith I should have some time too, if you want to tackle the linter first?

**Comment by simonsmith** [comment]
@timkelty Maybe just ignore it for now? That's what I did on a previous version of utils-flex

**Comment by timkelty** [comment]
oh ok :)

**Comment by timkelty** [comment]
Here's where I'm at right now: https://github.com/suitcss/components-grid/tree/remove-cell

**Comment by simonsmith** [comment]
Looking good

**Comment by giuseppeg** [comment]
@timkelty not sure if this could be an issue but keep in mind that the specificity of 

```css
.Grid--withGutter > * 
```

is lower than

```css
.Grid--withGutter > .Grid-cell 
```

**Comment by timkelty** [comment]
Yep. Not sure we can do much other than just be aware of it.
Seems like the reduced specificity may actually be a good thing, as long as it doesn't break other things.

Ya think?

**Comment by simonsmith** [comment]
The test suite is pretty decent. We can be reasonably confident with that

**Comment by giuseppeg** [comment]
Considering that you added this to the 4.0 milestone I think it is fine to make a breaking change.
