### ISSUE TITLE
NPM does not contain latest code

### ISSUE THREAD

**Issue by jenshedqvist** [suitcss/components-grid#55]
When I include the ^3.0.3 realase from NPM i don't get the latest features, this can be seen here:

Github source:
https://github.com/suitcss/components-grid/blob/master/lib/grid.css

NPM package:
https://npm.runkit.com/suitcss-components-grid/lib/grid.css?t=1516873254277

As you can see `Grid--fill` is missing and selectors are different (`> *` is missing) etc.

**Comment by simonsmith** [comment]
That will be because I forgot to release a new version! Apologies

Will get it done today

**Comment by jenshedqvist** [comment]
Good deal 👍

**Comment by simonsmith** [comment]
Done!
